Update shell-check.yml
Co-Authored-By: aayush <177418358+aayushrg7@users.noreply.github.com>

diff --git a/.github/workflows/shell-check.yml b/.github/workflows/shell-check.yml
--- a/.github/workflows/shell-check.yml
+++ b/.github/workflows/shell-check.yml
@@ -43,9 +43,4 @@ jobs:
 
       - name: Run ShellCheck Suggestion Mode
         run: |
-          results=$(shellcheck **/*.sh || true)
-          if [ -n "$results" ]; then
-            echo "::warning file=README.md::ShellCheck found issues:\n$results"
-          else
-            echo "::info::No issues found by ShellCheck."
-          fi
+          shellcheck **/*.sh || echo "::error ::ShellCheck found issues. Please check the comments in PR for suggestions."
